/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const AllrecipesLazyRouteImport = createFileRoute('/allrecipes')()
const IndexLazyRouteImport = createFileRoute('/')()

const AllrecipesLazyRoute = AllrecipesLazyRouteImport.update({
  id: '/allrecipes',
  path: '/allrecipes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/allrecipes.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/allrecipes': typeof AllrecipesLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/allrecipes': typeof AllrecipesLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/allrecipes': typeof AllrecipesLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/allrecipes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allrecipes'
  id: '__root__' | '/' | '/allrecipes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AllrecipesLazyRoute: typeof AllrecipesLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/allrecipes': {
      id: '/allrecipes'
      path: '/allrecipes'
      fullPath: '/allrecipes'
      preLoaderRoute: typeof AllrecipesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AllrecipesLazyRoute: AllrecipesLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
